#!/usr/bin/env bash

# Script transfers a file from client to a server and accepts 4 parameters
#1    The path to the file to be transferred.
#2    The IP of the server to transfer the file to.
#3    The username that scp connects with.
#4    The path to the SSH private key that scp uses.

if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
