#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
sudo chown -R ubuntu /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
