#!/usr/bin/env bash
# Fix the Apache server to run on the container and return a page containing
# "Hello Holberton" when querying the root of it
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
